const express = require("express");
const fetch = require("node-fetch");
const cors = require("cors");
const path = require("path");
const fs = require("fs");

// ── .env loader (no dependency) ───────────────────────────────────────
// Put GEMINI_API_KEY=AIza... in a .env file next to this one instead of
// exporting it in PowerShell every session. .env is gitignored, so the key
// never reaches the repo. A real environment variable always wins, and
// KANJI_NO_ENV_FILE=1 skips the file entirely (used by the R1 smoke test).
(function loadDotEnv() {
  if (process.env.KANJI_NO_ENV_FILE) return;
  try {
    for (const line of fs.readFileSync(path.join(__dirname, ".env"), "utf8").split(/\r?\n/)) {
      const m = /^\s*([\w.-]+)\s*=\s*(.*)\s*$/.exec(line);
      if (!m || line.trim().startsWith("#")) continue;
      const value = m[2].replace(/^(['"])(.*)\1$/, "$2");
      if (!(m[1] in process.env)) process.env[m[1]] = value;
    }
  } catch { /* no .env — perfectly normal */ }
})();

// ── Question sources ──────────────────────────────────────────────────
// 1. data/bank.json     — curated built-in bank (always available, offline)
// 2. data/ai-cache.json — questions generated by Gemini in the background,
//                         persisted to disk so they accumulate over time.
// The app NEVER waits on Gemini. If the API is rate-limited or the key is
// missing, everything still works from the local bank.

const BANK_PATH = path.join(__dirname, "data", "bank.json");
const CACHE_PATH = path.join(__dirname, "data", "ai-cache.json");
const CUSTOM_PATH = path.join(__dirname, "data", "custom.json");
const CACHE_MAX = 500;               // max AI questions kept on disk
const TOPUP_COOLDOWN_MS = 10 * 60 * 1000; // min gap between Gemini attempts

const bank = JSON.parse(fs.readFileSync(BANK_PATH, "utf8"));

let aiCache = [];
try {
  aiCache = JSON.parse(fs.readFileSync(CACHE_PATH, "utf8"));
  if (!Array.isArray(aiCache)) aiCache = [];
} catch { aiCache = []; }

function saveCache() {
  try {
    fs.writeFileSync(CACHE_PATH, JSON.stringify(aiCache, null, 1), "utf8");
  } catch (e) {
    console.log("  [cache] could not save:", e.message);
  }
}

// ── User-added custom cards ───────────────────────────────────────────
let customCards = [];
try {
  customCards = JSON.parse(fs.readFileSync(CUSTOM_PATH, "utf8"));
  if (!Array.isArray(customCards)) customCards = [];
} catch { customCards = []; }

function saveCustom() {
  try {
    fs.writeFileSync(CUSTOM_PATH, JSON.stringify(customCards, null, 1), "utf8");
  } catch (e) {
    console.log("  [custom] could not save:", e.message);
  }
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ── Gemini background top-up (never blocks a request) ─────────────────
// Parameterised by JLPT level so generated questions match the difficulty of
// the kanji being asked about (N5 easiest → N1 hardest).
function systemPrompt(level) {
  return `You are a JLPT ${level} Japanese teacher. Return ONLY a valid JSON array — no markdown, no backticks, no extra text before or after.
Each element must have exactly these keys:
- kanji: string (the word being tested; keep it at JLPT ${level} difficulty)
- sentence: string (natural Japanese sentence at JLPT ${level} level; wrap the target in [[double brackets]] e.g. "[[覆す]]")
- reading: string (correct hiragana reading)
- meaning: string (English meaning)
- type: "on" or "kun"
- hint: string (one-sentence memory tip about the reading pattern)
- compounds: array of 2-3 strings like "覆面 (fukumen) — mask"
- distractors: array of exactly 3 plausible WRONG hiragana readings (believable misreadings, never the correct answer)
Keep sentences short (under 25 characters). Return all items in a single complete JSON array.`;
}

// Constrain the model to the shape instead of asking for JSON in the prompt.
const QUESTION_SCHEMA = {
  type: "ARRAY",
  items: {
    type: "OBJECT",
    properties: {
      kanji: { type: "STRING" },
      sentence: { type: "STRING" },
      reading: { type: "STRING" },
      meaning: { type: "STRING" },
      type: { type: "STRING", enum: ["on", "kun"] },
      hint: { type: "STRING" },
      compounds: { type: "ARRAY", items: { type: "STRING" } },
      distractors: { type: "ARRAY", items: { type: "STRING" } }
    },
    required: ["kanji", "sentence", "reading", "meaning", "type", "hint", "compounds", "distractors"],
    propertyOrdering: ["kanji", "sentence", "reading", "meaning", "type", "hint", "compounds", "distractors"]
  }
};

// If the whole reply won't parse (truncation, one stray character), salvage the
// items that do parse by scanning balanced top-level {...} blocks.
function parseQuestions(text) {
  const clean = text.replace(/```json|```/g, "").trim();
  try {
    const arr = JSON.parse(clean);
    if (Array.isArray(arr)) return arr;
    if (arr && typeof arr === "object") return [arr];
  } catch { /* fall through to salvage */ }

  const out = [];
  let depth = 0, start = -1, inStr = false, esc = false;
  for (let i = 0; i < clean.length; i++) {
    const c = clean[i];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') inStr = true;
    else if (c === "{") { if (depth++ === 0) start = i; }
    else if (c === "}" && depth > 0 && --depth === 0 && start >= 0) {
      try { out.push(JSON.parse(clean.slice(start, i + 1))); } catch { /* skip */ }
      start = -1;
    }
  }
  return out;
}

let lastTopupAttempt = 0;
let topupRunning = false;

function validQuestion(q) {
  return q && typeof q.kanji === "string" && typeof q.sentence === "string" &&
    /\[\[.+\]\]/.test(q.sentence) && typeof q.reading === "string" &&
    typeof q.meaning === "string" && (q.type === "on" || q.type === "kun") &&
    typeof q.hint === "string" && Array.isArray(q.compounds) &&
    Array.isArray(q.distractors) && q.distractors.length === 3 &&
    !q.distractors.includes(q.reading);
}

// Tried in order — each model has its own separate free-tier quota, so when
// one is rate-limited another often still works.
// Google retires model names (1.5 and 2.0 are already shut down), so lead with
// the `-latest` alias, which Google hot-swaps to the current release. The SPA
// goes further and discovers the list from ListModels at runtime.
const GEMINI_MODELS = [
  "gemini-flash-latest",
  "gemini-3.5-flash-lite",
  "gemini-3.6-flash",
  "gemini-2.5-flash"
];

async function callGemini(apiKey, model, userMsg, sysPrompt, structured = true) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  const payload = {
    systemInstruction: { parts: [{ text: sysPrompt }] },
    contents: [{ role: "user", parts: [{ text: userMsg }] }],
    // temperature/top_p are deprecated; token headroom for reasoning models.
    generationConfig: structured
      ? { maxOutputTokens: 8192, responseMimeType: "application/json", responseSchema: QUESTION_SCHEMA }
      : { maxOutputTokens: 8192 }
  };
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });
  // Not every model accepts a response schema — fall back to plain text once.
  if (structured && response.status === 400) return callGemini(apiKey, model, userMsg, sysPrompt, false);
  if (response.status === 429) throw new Error("rate limited");
  const data = await response.json();
  if (!response.ok) throw new Error(data.error?.message || "Gemini API error");
  // Reasoning models emit thought parts alongside the answer — keep the answer.
  return (data.candidates?.[0]?.content?.parts || [])
    .filter(p => typeof p.text === "string" && !p.thought)
    .map(p => p.text).join("");
}

// Fire-and-forget: generate fresh sentence variants for a few kanji and
// persist them. Failures are silent — the local bank keeps working.
function backgroundTopup() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || topupRunning) return;
  if (Date.now() - lastTopupAttempt < TOPUP_COOLDOWN_MS) return;
  if (aiCache.length >= CACHE_MAX) return;

  lastTopupAttempt = Date.now();
  topupRunning = true;

  (async () => {
    try {
      // Pick ONE level per batch so the prompt and the generated questions
      // stay at a single, coherent difficulty. Legacy bank items with no
      // level are treated as N1.
      const levels = [...new Set(bank.map(q => q.level || "N1"))];
      const level = shuffle(levels)[0];
      const inLevel = bank.filter(q => (q.level || "N1") === level);
      const kanji = shuffle(inLevel.map(q => q.kanji)).slice(0, 8);
      console.log(`  [ai top-up] requesting ${level} variants for:`, kanji.join("、"));
      const sys = systemPrompt(level);
      const prompt = `Create DIFFERENT ${level}-level quiz questions for these kanji — new sentences, vary the context. Kanji: ${kanji.join("、")}`;

      let text = null, lastErr = null;
      for (const model of GEMINI_MODELS) {
        try {
          text = await callGemini(apiKey, model, prompt, sys);
          console.log(`  [ai top-up] ${model} responded`);
          break;
        } catch (e) {
          lastErr = e;
          console.log(`  [ai top-up] ${model} failed (${e.message}) — trying next model`);
        }
      }
      if (text === null) throw lastErr || new Error("all models failed");

      // Tag each generated question with the batch level.
      const items = parseQuestions(text).filter(validQuestion).map(q => ({ ...q, level }));
      if (items.length) {
        aiCache.push(...items);
        if (aiCache.length > CACHE_MAX) aiCache = aiCache.slice(-CACHE_MAX);
        saveCache();
        console.log(`  [ai top-up] +${items.length} questions cached (total ${aiCache.length})`);
      }
    } catch (e) {
      console.log(`  [ai top-up] skipped (${e.message}) — local bank still serving`);
    } finally {
      topupRunning = false;
    }
  })();
}

// ── Server ────────────────────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));
// The frontend loads data/*.json directly (see public/index.html), so it runs
// identically here and on the static GitHub Pages build. Serving data/ keeps
// local dev on exactly the same code path as production.
app.use("/data", express.static(path.join(__dirname, "data")));

// Full merged question bank. Retained for the R1 offline smoke test and as a
// convenience endpoint; the SPA no longer depends on it.
app.get("/api/bank", (req, res) => {
  res.json({
    questions: [...bank, ...customCards, ...aiCache],
    aiCount: aiCache.length,
    customCount: customCards.length
  });
  backgroundTopup(); // opportunistic, after responding
});

// Add a custom card. kanji + reading required, sentence optional.
app.post("/api/custom", (req, res) => {
  const kanji = (req.body.kanji || "").trim();
  const reading = (req.body.reading || "").trim();
  const sentence = (req.body.sentence || "").trim();
  const meaning = (req.body.meaning || "").trim();

  if (!kanji || !reading) {
    return res.status(400).json({ error: "kanji and reading are required" });
  }
  if (!/^[ぁ-んー]+$/.test(reading)) {
    return res.status(400).json({ error: "reading must be hiragana" });
  }
  if (customCards.some(c => c.kanji === kanji)) {
    return res.status(409).json({ error: `「${kanji}」 is already in your cards` });
  }

  const card = {
    kanji,
    reading,
    // If no sentence given, show the word alone; [[target]] markup still applies.
    sentence: sentence
      ? (sentence.includes("[[") ? sentence : sentence.replace(kanji, `[[${kanji}]]`))
      : `[[${kanji}]]`,
    meaning: meaning || "",
    custom: true
  };
  // If the sentence didn't contain the kanji, fall back to appending it.
  if (!card.sentence.includes("[[")) card.sentence = `${sentence}　→ [[${kanji}]]`;

  customCards.push(card);
  saveCustom();
  res.json({ ok: true, cards: customCards });
});

app.get("/api/custom", (req, res) => res.json({ cards: customCards }));

app.delete("/api/custom/:kanji", (req, res) => {
  const before = customCards.length;
  customCards = customCards.filter(c => c.kanji !== req.params.kanji);
  if (customCards.length !== before) saveCustom();
  res.json({ ok: true, cards: customCards });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`\n✅ Kanji Quiz (N5–N1) running at http://localhost:${PORT}`);
  console.log(`   ${bank.length} built-in questions · ${aiCache.length} AI-cached`);
  console.log(process.env.GEMINI_API_KEY
    ? "   GEMINI_API_KEY set — fresh questions will be added every 10 minutes."
    : "   No GEMINI_API_KEY (.env or environment) — running fully offline from the local bank (that's fine).");
  backgroundTopup();
  // Keep generating while the server runs, even with no quiz activity.
  // backgroundTopup() itself enforces the cooldown and the 500-item cache cap.
  setInterval(backgroundTopup, TOPUP_COOLDOWN_MS + 5000);
});
